// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo8AH5p5dCU5-8VjEy7TYUPfokPhCMxrE',
    appId: '1:836579737794:web:5b2d73eaa849cb25213b5b',
    messagingSenderId: '836579737794',
    projectId: 'sportup-948f8',
    authDomain: 'sportup-948f8.firebaseapp.com',
    storageBucket: 'sportup-948f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgNtV_V_DdoPXSMA8C-GtgZU0BXF7OXAA',
    appId: '1:836579737794:android:2d45d00bc90ad16d213b5b',
    messagingSenderId: '836579737794',
    projectId: 'sportup-948f8',
    storageBucket: 'sportup-948f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNlsWFgCb-EzsYiX6P-jHo2_jIO6ypvSk',
    appId: '1:836579737794:ios:ada1c158669375a2213b5b',
    messagingSenderId: '836579737794',
    projectId: 'sportup-948f8',
    storageBucket: 'sportup-948f8.appspot.com',
    iosClientId: '836579737794-n90g35md1pqnqcmj2aaf21nispe38i15.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNlsWFgCb-EzsYiX6P-jHo2_jIO6ypvSk',
    appId: '1:836579737794:ios:ada1c158669375a2213b5b',
    messagingSenderId: '836579737794',
    projectId: 'sportup-948f8',
    storageBucket: 'sportup-948f8.appspot.com',
    iosClientId: '836579737794-n90g35md1pqnqcmj2aaf21nispe38i15.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportUp',
  );
}
